export const CHANGE_STYLE_GUIDE_MODE = 'CHANGE_STYLE_GUIDE_MODE';
export const GET_EBUCKLEY = 'GET_EBUCKLEY';
export const CHANGE_THEME = 'CHANGE_THEME';
export const TOGGLE_NAV_DROPDOWN = 'TOGGLE_NAV_DROPDOWN';
export const TOGGLE_SOCIAL_DROPDOWN = 'TOGGLE_SOCIAL_DROPDOWN';